### 1. 파이썬 리스트와 넘파이

In [2]:
import numpy as np            # numpy의 별칭으로 np를 지정함

a = np.array([2, 3, 4])       # 넘파이 ndarray 객체의 생성
a
type(a)

numpy.ndarray

### 2. 다차원 배열의 속성들

In [3]:
# a 객체의 형상(shape), 차원, 요소의 자료형, 요소의 크기(byte), 요소의 수
a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('int64'), 8, 3)

In [7]:
b = np.array([[2, 3, 4], [6, 7, 8]])
b.shape, b.ndim, b.dtype

((2, 3), 2, dtype('int64'))

In [8]:
a = np.array([10, 20, 30])     # 넘파이 ndarray 객체 a 생성
b = np.array([1, 2, 3])        # 넘파이 ndarray 객체 b 생성

In [9]:
a + b

array([11, 22, 33])

In [10]:
a - b

array([ 9, 18, 27])

In [11]:
a * b

array([10, 40, 90])

In [12]:
a / b

array([10., 10., 10.])

### 3. 다차원 배열과 브로드캐스팅

In [13]:
a = np.array([10, 20 ,30])
a * 10

array([100, 200, 300])

In [14]:
a + 10

array([20, 30, 40])

In [15]:
b = np.array([[10, 20, 30],
              [40, 50, 60]])
c = np.array([2, 3, 4])       # [[2, 3, 4], [2, 3, 4]] 배열로 변환된 후 덧셈을 병렬적으로 수행함
b + c

array([[12, 23, 34],
       [42, 53, 64]])